version: '3.9'

services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - skoredb:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=skore_development

volumes:
  skoredb:
